# .codex/config.toml

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest", "--isolated"]

[mcp_servers.supabase]
url = "https://mcp.supabase.com/mcp?project_ref=pdcntbiyzzlvuhhkuihe"

[features]
rmcp_client = true

[mcp_servers.shadcn]
command = "npx"
args = ["shadcn@latest", "mcp"]

[mcp_servers.filesystem]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-filesystem", "C:\\Users\\Rovaron\\Desktop\\mvp-concurso\\micro-saas-mvp"]